# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='yt_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='yt_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
