# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20161102_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboard',
            name='week',
            field=models.CharField(max_length=100),
        ),
    ]
