# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_song_yt_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='yt_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
