# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_fbuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbuser',
            name='state',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
