# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_fbuser_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbuser',
            name='yt_access_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='fbuser',
            name='yt_refresh_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
