# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_auto_20161114_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbuser',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
